### ISSUE TITLE
Manage Publication Type Templates

### ISSUE THREAD

**Issue by godboko** [xaraya/modules#1]
So I was thinking it might be nice if the page showed the path so it was easier to determine which file permissions needed to be changed, 

Also think it would be neat if there was a "download" option that way one can view the file locally or just download the changes if they don't want to change the file permissions.

**Comment by random777** [comment]
Second one can be done. Not a problem.
For the first I guess we could show the relative path from the toot dir? Otherwise we show the entire real path. Not sure that is a good thing.

**Comment by godboko** [comment]
With almost a year to think on it I think you are correct sir! Good job on the updates.
